---

Id: farag2.SophiaScript
Version: 5.3.2
Name: Sophia Script
Publisher: farag2
License: MIT
LicenseUrl: https://github.com/farag2/Windows-10-Sophia-Script/blob/master/LICENSE
AppMoniker: Sophia
Tags: sophia, script, debloat
Description: A PowerShell module for Windows 10 fine-tuning and automating the routine tasks
Homepage: https://github.com/farag2/Windows-10-Sophia-Script
Installers:
  - Arch: x64
    Url: https://github.com/farag2/Windows-10-Sophia-Script/releases/download/5.3.2/Sophia.v5.3.2.zip
    Sha256: 5EDA5C4F53BAC13E18EA99A19EAB628819224644BBCE7798BD1D7251970E8477
    InstallerType: zip
